---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    aws_access_key: "YOUR_AWS_ACCESS_KEY"
    aws_secret_key: "YOUR_AWS_SECRET_KEY"
    region: "us-east-1"  # Change to your desired AWS region
    instance_type: "t2.micro"  # Change to your desired instance type
    ami_id: "ami-XXXXXXXXXXXXXXXXX"  # Change to the desired AMI ID
    key_pair: "YOUR_KEY_PAIR_NAME"  # Change to your key pair name
    security_group: "YOUR_SECURITY_GROUP"  # Change to your security group name
    subnet_id: "YOUR_SUBNET_ID"  # Change to your subnet ID
    ec2_tag_name: "MyEC2Instance"  # Change to your desired instance name
  tasks:
    - name: Create EC2 Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_pair }}"
        security_groups: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        count: 1
        wait: yes
        instance_tags:
          Name: "{{ ec2_tag_name }}"
      register: ec2

    - name: Add new EC2 instance to hosts group
      add_host:
        name: "{{ ec2.instances[0].public_ip }}"
        groups: ec2_instances

- name: Print EC2 Instance IP
  hosts: localhost
  tasks:
    - name: Print the IP address of the new EC2 instance
      debug:
        msg: "New EC2 instance IP address: {{ hostvars[groups['ec2_instances'][0]].ansible_host }}"

