---
- name: Create Azure VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Azure Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ prefix }}-rg"
        location: "{{ azure_region }}"

    - name: Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ prefix }}-rg"
        name: "{{ prefix }}-vnet"
        address_prefixes: ["10.0.0.0/16"]  # Replace with your desired address prefix
        location: "{{ azure_region }}"

    - name: Create Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ prefix }}-rg"
        virtual_network_name: "{{ prefix }}-vnet"
        name: "{{ prefix }}-subnet"
        address_prefix: "10.0.0.0/24"  # Replace with your desired subnet address prefix

    - name: Reserve a static IP Address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ prefix }}-rg"
        allocation_method: Static
        name: "{{ prefix }}-pip"
        location: "{{ azure_region }}"
      register: public_ip_result

    - name: Create a Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ prefix }}-rg"
        name: "{{ prefix }}-nsg"
        rules:
          - name: SSH
            protocol: Tcp
            priority: 123
            destination_port_range: 22
            access: Allow
            direction: Inbound

    - name: Create Network Interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ prefix }}-rg"
        name: "{{ prefix }}-nic"
        virtual_network: "{{ prefix }}-vnet"
        subnet: "{{ prefix }}-subnet"
        security_group: "{{ prefix }}-nsg"
        ip_configurations:
        - name: ipconfig1
          public_ip_name: "{{ prefix }}-pip"
          primary: True

    - name: Create Virtual Machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ prefix }}-rg"
        name: "{{ prefix }}-vm"
        vm_size: "{{ vmSize }}"
        managed_disk_type: Premium_LRS
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"  # Use an Ansible vault to securely store the password
        network_interfaces: "{{ prefix }}-nic"
        image:
          offer: RHEL
          publisher: RedHat
          sku: 9-LVM
          version: latest

    - name: Display VM Public IP
      debug:
        msg: "Your public IP address is: {{ public_ip_result.state.ip_address }}"

