---
- name: Creating an EC2 Instance with Creating a VPC and Subnet Id
  hosts: localhost
  tasks:

    - name: Create EC2 SSH key pair
      amazon.aws.ec2_key:
        name: "{{ prefix }}-ssh-key"
        region: "{{ region }}"
      no_log: true
      register: aws_ec2_key_pair

    - name: Create VPC Network
      amazon.aws.ec2_vpc_net:
        name: "{{ prefix }}-vpc_net"
        cidr_block: "{{ cidr_block }}"
        region: "{{ region }}"
      register: vpc
  
    - name: Create VPC Network
      amazon.aws.ec2_vpc_subnet:
        cidr: "{{ cidr }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
      register: subnet

    - name: Create a Security Group  
      amazon.aws.ec2_security_group:
        name: "{{ prefix }}-security_group"
        description: "{{ prefix }}-test-sg"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all on port 80"
          - proto: tcp
            ports:
            - 22 
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all on port 22"
      register: security_group
    
    - name: Create Virtual Machine
      amazon.aws.ec2_instance:
        name: "{{ prefix }}-vm"
        key_name: "{{ prefix }}-ssh-key"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group.group_id  }}"
        count: 1
        wait: yes
        wait_timeout: 600
        aws_region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ ami }}"
      register: vm

    - name: Gathering VM information using instance ID 
      amazon.aws.ec2_instance_info:
        instance_ids: "{{ vm.instance_ids[0] }}"
        region: "{{ region }}"
      register: info

    - name: Display VM Public IP
      debug:
        msg: "Your public IP address is: {{ info.instances[0].public_ip_address }}"



