---
- name: Create virtual machine instance in GCP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create fixed disk for OS image
      google.cloud.gcp_compute_disk:
        name: "{{ prefix }}-disk"
        size_gb: "{{ disk_size }}"
        source_image: "{{ source_image }}"
        zone: "{{ zone }}"
        state: present
      register: disk
    
    - name: Create VPC Network
      google.cloud.gcp_compute_network:
        name: "{{ prefix }}-network"
        auto_create_subnetworks: false
        state: present
      register: network

    - debug:
        var: network

    - name: Create Subnet
      google.cloud.gcp_compute_subnetwork:
        name: "{{ prefix }}-subnet"
        region: "{{ region }}"
        ip_cidr_range: "{{ subnet_cidr }}"
        network: "{{ network }}"
        state: present
      register: subnet

    - name: Reserve a static IP Address
      google.cloud.gcp_compute_address:
        name: "{{ prefix }}-ip"
        region: "{{ region }}"
        state: present
      register: address

    - name: Create Virtual Machine
      google.cloud.gcp_compute_instance:
        state: present
        name: "{{ prefix }}-vm"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: "{{ network }}"
            subnetwork: "{{ subnet }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
                nat_ip: "{{ address }}"

    - name: Configuring firewall to allow SSH access
      google.cloud.gcp_compute_firewall:
        name: "{{ prefix }}-ssh-rule"
        direction: "ingress"
        disabled: "false"
        allowed:
        - ip_protocol: tcp
          ports:
          - '22'
        network: "{{ network }}"
        priority: "1000"
        source_ranges: "0.0.0.0/0"
        state: present

    - name: Display VM Public IP
      debug:
        msg: "Your public IP address is: {{ network.address.address }}"

