---
- name: Create GCP VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create GCP Instance
      gcp_compute_instance:
        name: my-vm  # Replace with your desired VM name
        machine_type: zones/us-central1-a/machineTypes/n1-standard-1  # Replace with your desired machine type and zone
        zone: us-central1-a  # Replace with your desired GCP zone
        project: your-project-id  # Replace with your GCP project ID
        auth_kind: serviceaccount
        service_account_file: /path/to/your-service-account.json  # Replace with the path to your GCP service account JSON key file
        image: projects/debian-cloud/global/images/debian-9-stretch-v20220913  # Replace with your desired image
        state: present
        tags:  # Replace with your desired tags
          - http-server
          - https-server
        metadata:
          items:
            - key: ssh-keys
              value: "your-ssh-key"  # Replace with your SSH key
      register: gcp_vm

    - name: Display GCP VM IP Address
      debug:
        var: gcp_vm.instance.networkInterfaces[0].accessConfigs[0].natIP
